name: Deploy Spring Boot (Docker)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build JAR
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test

    - name: Build & Push Docker Image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t ${{ secrets.DOCKER_USERNAME }}/community-server:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/community-server:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      env:
        MYSQL_URL: ${{ secrets.MYSQL_URL }}
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        FILE_UPLOAD_PATH: ${{ secrets.FILE_UPLOAD_PATH }}
        SSL_CERT: ${{ secrets.SSL_CERT }}
        SSL_KEY: ${{ secrets.SSL_KEY }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: MYSQL_URL, MYSQL_USERNAME, MYSQL_PASSWORD, SSL_CERT, SSL_KEY
        script: |
          cd ~/community
          git fetch --all
          git reset --hard origin/main
          
          echo "$SSL_CERT" > ./nginx/cert.pem
          echo "$SSL_KEY" > ./nginx/key.pem
          
          echo "MYSQL_URL=$MYSQL_URL" > .env
          echo "MYSQL_USERNAME=$MYSQL_USERNAME" >> .env
          echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
          echo "FILE_UPLOAD_PATH=file:/app/upload/" >> .env
          
          docker compose pull
          docker compose down
          docker compose up -d
